version: '3.8'
services:
  music-disc:
    image: hmes98318/music-disc:1.2.3
    container_name: music-disc
    restart: always
    environment:
      TOKEN: "your_token"
      PREFIX: "-"
      PLAYING: "-play | RZJoKeRRRR"
      COLOR: "#FFFFFF"
      DEFAULTVOLUME: 50
      AUTO_LEAVE: "true"
      DISPLAY_VOICE_STATE: "true"
    ports:
      - 33333:33333
